### ISSUE TITLE
Practice 3

### ISSUE THREAD

**Issue by geopimik** [dmytrozabolotnii/autoware_mini_practice#2]
#### Please fix the following:

1. I would assign these from **local variables** to **class variables** together at the very end of the `path_callback`
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/fbc6d92e47c2f2521532959d51dbfdd9efec0187/practice_3/nodes/control/pure_pursuit_follower.py#L31
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/fbc6d92e47c2f2521532959d51dbfdd9efec0187/practice_3/nodes/control/pure_pursuit_follower.py#L42
   - Since both global variables are used in `current_pose_callback` that runs 50Hz...
   - When assigning them from path_callback that can run much longer we can create a situation when they are not in sync.
   - It should not happen currently, since we don't recreate the path, but in later stages when we will implement global planner it could happen.

2. Same loop is done twice. Reorganize the code so that it is done only once.
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/fbc6d92e47c2f2521532959d51dbfdd9efec0187/practice_3/nodes/control/pure_pursuit_follower.py#L29
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/fbc6d92e47c2f2521532959d51dbfdd9efec0187/practice_3/nodes/control/pure_pursuit_follower.py#L35

3. I'm against using the `max` there:
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/fbc6d92e47c2f2521532959d51dbfdd9efec0187/practice_3/nodes/control/pure_pursuit_follower.py#L50
   - your `lookahead_point` coordinates will stop progressing after reaching path end, so with `max` you will override the real distance, but the `lookahead_heading` will still be calculated using the `lookahead_point`. So the values in the formula will be wrong.
   - If you can convince me it is OK, then you can keep it.

**Comment by dmytrozabolotnii** [comment]
Fixed in # ba865eb32462f590d89f118b50cb97243c775ecd
Re 3: max is supposed to prevent erratic behaviour near the end of planned path, however it would be incorrect implementation of planner, so I removed it. It is probably something that should be fixed in bicycle simulation by introducing maximum heading angle rate change.

**Comment by geopimik** [comment]
OK
