### ISSUE TITLE
Practice 4 - global planner code

### ISSUE THREAD

**Issue by geopimik** [dmytrozabolotnii/autoware_mini_practice#3]
#### Please fix the following:
1. Unnecessary `return`s'
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/f703171db7410feaf9cb6ed24243c66435f6d228/practice_4/nodes/planning/global/lanelet2_global_planner.py#L49
   - https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/f703171db7410feaf9cb6ed24243c66435f6d228/practice_4/nodes/planning/global/lanelet2_global_planner.py#L97

2. Both are in km/h, why only one divided by 3.6 https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/f703171db7410feaf9cb6ed24243c66435f6d228/practice_4/nodes/planning/global/lanelet2_global_planner.py#L106

**Comment by dmytrozabolotnii** [comment]
Fixed in # 032f11e67ae9e106703e4a7cc9b1cbecdadb2b5d

**Comment by geopimik** [comment]
If there is no `speed_ref`, the `self.speed_limit` will be used as speed in `waypoint.twist.twist.linear.x = speed`
I see one problem there!

https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/b1b67c3c4635d3d1995a1d1b7550788b15e0b4dc/practice_4/nodes/planning/global/lanelet2_global_planner.py#L102-L114

**Comment by dmytrozabolotnii** [comment]
Fixed in # 2fa52d391f7ac04c0ec36ef93d6c2b85a331bf6c, my bad.

**Comment by geopimik** [comment]
OK.
