### ISSUE TITLE
Practice 5 - points_clusterer

### ISSUE THREAD

**Issue by geopimik** [dmytrozabolotnii/autoware_mini_practice#5]
A bit more informative message could be useful :), adding the node name might also help.
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/464bf162f8b3c9071dcc12165b5f148d9f870ab7/practice_5/nodes/detection/lidar_cluster/points_clusterer.py#L32

**Comment by dmytrozabolotnii** [comment]
Fixed in c7172c96b4dd22b8f547e1c7c4d30461c6614b7c

**Comment by geopimik** [comment]
OK
