### ISSUE TITLE
Practice 5 - cluster_detector

### ISSUE THREAD

**Issue by geopimik** [dmytrozabolotnii/autoware_mini_practice#6]
1. I think you are missing the last object here. You also have to consider that there might actually be no objects.
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/464bf162f8b3c9071dcc12165b5f148d9f870ab7/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L60

2. Then I have a wired thing when running you practice 5 files, then I see in rviz only very few convex hulls. Although in the message you publish (`/detection/lidar/detected_objects`) there seems to be a lot more of them... Do you see them all in rviz?

What I see with your code:
![image](https://github.com/dmytrozabolotnii/autoware_mini_practice/assets/33843059/0a72e681-564a-4006-842b-e3eda6130432)

How it should be:
![image](https://github.com/dmytrozabolotnii/autoware_mini_practice/assets/33843059/d207d371-7cab-4c6b-ae93-9a84825cb1b8)

**Comment by dmytrozabolotnii** [comment]
Fixed in c7172c96b4dd22b8f547e1c7c4d30461c6614b7c

**Comment by dmytrozabolotnii** [comment]
No objects edge case is fixed in 6671d2507a8a01016a6811428ee9f19e809b9543

**Comment by geopimik** [comment]
OK
