### ISSUE TITLE
Practice 6 - simple_local_planner - code comments

### ISSUE THREAD

**Issue by geopimik** [dmytrozabolotnii/autoware_mini_practice#7]
Please fix following:
1. Copying global variables to local variables should be done before checking if they are None. And you need to check the local variables then. Currently at the time of checking the global variable might not be None, but when code reaches the copying part it might already be None.
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/d400477d12f5e13010bf1c99c95fe5ed7393a048/practice_6/nodes/planning/local/simple_local_planner.py#L89-L98

2. From the previous point I would check all the local variables that you copy from global ones and actually use later in the callback

3. Just discussion point: having `current_position` in the `self.lock` group I'm so and so. It comes from a different callback than the global path related stuff and is updated 50Hz. In some sense, we want to get the latest updated `curret_position` as possible, so it doesn't need to be in that `self.lock` group, but it wouldn't change much if we brought it out from there.

4. You need to wrap it around try-except block to catch possible exceptions. See [example from previous practice]. And a warning message should be printed to console saying that there was problem with transform and zero speed is assumed. Currently if something goes wrong in the transform the callback will stop there with error in console and local planning is not functional any more.
(https://github.com/dmytrozabolotnii/autoware_mini_practice/tree/main/practice_5#5-get-data-in-cluser_detector-node).
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/d400477d12f5e13010bf1c99c95fe5ed7393a048/practice_6/nodes/planning/local/simple_local_planner.py#L110-L112

5. This calculation is wrong - with moving obstacle it should be moving along with them within the distance of `self.braking_safety_distance_obstacle`
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/d400477d12f5e13010bf1c99c95fe5ed7393a048/practice_6/nodes/planning/local/simple_local_planner.py#L156-L157

**Comment by dmytrozabolotnii** [comment]
Fixed in 79a88b91fddb4f5720ee1c8ddf40317a551a5b51

**Comment by geopimik** [comment]
1. Ok
2. Ok
3. Ok
4. We don't want to return if getting the transform fails. We want to continue with code, but we will assume everything to be static obstacles
5. Ok

**Comment by dmytrozabolotnii** [comment]
Fixed in 4e83776ddba3fadd9801d436cb85959754efebc1 for Practices 6 and 7

**Comment by geopimik** [comment]
OK
