### ISSUE TITLE
Practice 7 - camera_traffic_light_detector - code comments

### ISSUE THREAD

**Issue by geopimik** [dmytrozabolotnii/autoware_mini_practice#8]
#### Comments
1. The second `if` is useless because you already have the check in first `if`
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/53842608adb69ee0c211ddb7da4fe1956d595776/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L133-L139

2. No need to create - used only locally inside the if
https://github.com/dmytrozabolotnii/autoware_mini_practice/blob/53842608adb69ee0c211ddb7da4fe1956d595776/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L156

**Comment by dmytrozabolotnii** [comment]
Fixed in 37d63eb64940658861369fdd571bd4119aebee9f

**Comment by geopimik** [comment]
ok
